# Generated by Django 2.2.18 on 2021-09-09 10:41
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0095_fix_attr_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinkertoken',
            name='shop',
        ),
        migrations.AddField(
            model_name='baselinkertoken',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bl_token', to='shuup.Supplier'),
        )
    ]
