# Generated by Django 2.2.18 on 2021-09-22 17:16

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('shuup', '0098_product_presale'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='fetch_all_db',
            field=models.BooleanField(default=False),
        ),
    ]
