# Generated by Django 2.2.18 on 2021-07-19 06:23

from django.db import migrations, models
import django.db.models.deletion
from jsonfield import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0099_supplier_fetch_all_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLinkerCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', JSONField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bl_categories', to='shuup.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        ]
