# Generated by Django 2.2.18 on 2022-02-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0100_baselinkercategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='horizontal_ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]