# Generated by Django 2.2.18 on 2022-02-06 12:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0101_auto_20220204_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLinkerProductProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shuup.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
