# Generated by Django 2.2.18 on 2022-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0102_baselinkerproductproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinkertoken',
            name='inventory',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
